### ISSUE TITLE
while function not workin properly

### ISSUE THREAD

**Issue by Payton212** [Payton212/SKATE#8]
after doing some digging i have found that the while loop is not checking to see if the trick is unique or not when i was trying to add logic to also not return a value that all none; if you log the named trick in easy you will find that some tricks are repeating;
not sure why need to figure out reason

**Comment by cunnellp5** [comment]
Build an array of completed tricks and check against that, instead. that should simplify the do while logic. And perhaps reveal a way to get rid of the do while

**Comment by Payton212** [comment]
I like that! I had the thought of just putting the all none in the completedTricks array but to completely get rid of it wouldn’t be bad and just if it matches one in the array like you said I like that!!

**Comment by cunnellp5** [comment]
Another thought could be:

- have an array full of tricks
- pick one randomly
- move it to another array

that way you wouldnt even have to have any checks

**Comment by Payton212** [comment]
Would we just have like 10 arrays for obstacles n stuff? Or how would we do that??

**Comment by cunnellp5** [comment]
Unsure without understanding the app as a whole
Having user stories and a list of features would help answer that

**Comment by cunnellp5** [comment]
for example what are all the possible obstacles that would be acceptable?

If its generating a trick, randomly, you could build a big object in a way that includes certain obstacles.

Then based on the chosen filters or obstacles you could generate a list of acceptable tricks. Which would be the bucket you can take from and put into a completedTrick array.

I think there can be many ways to approach it. And you could have many arrays to keep track. But i think that would get messy and become an exercise in organizing skate tricks rather than filtering through data

Here's a quick thought
```js
const tricksLibrary = {
  easy: [
    { 
      trickName: 'ollie', 
      stance: STANCES.REGULAR, 
      direction: DIRECTIONS.NONE, 
      bodyRotation: 0, 
      shuvRotation: 0, 
      flip: FLIPS.NONE, 
      acceptableObstacles: ['flat', 'ramp', 'step up'] 
    },
  ],
  medium: [
    {}
  ],
  hard: [
    {}
  ]
}
```

Each trick can be an object inside of a difficulty array. The object itself can have all the information the trick could care about

if the user selected 'easy' and 'REGULAR' stance only, then you could build an array like

```js
const userSelectedFilters = {
   difficulty: 'easy',
   stance: 'regular'
}

const filteredTrickArray = tricksLibrary.[${userSelectedFilters.difficulty}].filter((trick) => {
    return trick.stance === userSelectedFilters.stance
})
```

the above example is contrived would need massaging for multiple filters, but that would effectively build a new array of all easy tricks with a regular stance.

since the array would be generated on the fly based on some logic, you wouldnt have to worry about building a lot of arrays for different obstacles

**Comment by cunnellp5** [comment]
could flatten it to be something like: 

```js
const tricksLibrary = [
  { 
    trickName: 'ollie',
    stance: STANCES.REGULAR,
    direction: DIRECTIONS.NONE,
    bodyRotation: 0,
    shuvRotation: 0,
    flip: FLIPS.NONE,
    acceptableObstacles: ['flat', 'ramp', 'step up'],
    difficulty: DIFFICULTY.EASY
  },
]
```

Then you could do filtering in steps and might be a little simpler to start out with

for example:

```js
const listOfEasyTricks = tricksLibrary.filter((trick) => trick.difficulty === "easy");
const listOfRegularStanceTricks = easyTricks.filter((trick) => trick.stance === "regular");
```

**Comment by cunnellp5** [comment]
Maybe even: 

```js
const tricksLibrary = [
  { 
    trickName: 'ollie',
    trickConfig: {
        stance: STANCES.REGULAR,
        direction: DIRECTIONS.NONE,
        bodyRotation: 0,
        shuvRotation: 0,
        flip: FLIPS.NONE,
    },
    obstacles: [...allObstacles],
    difficulty: DIFFICULTY.EASY
  },
]
```

**Comment by Payton212** [comment]
given all the new ideas we've talked about do you think this would still be the best way to accomplish the current goals?
and if you're still working it out feel free to not reply!

**Comment by cunnellp5** [comment]
yeah i think this is at least better than what is in place, currently. maybe not perfect, but i think its a little better because

1. you'll be able to filter this array of objects for difficulty
2. you could randomly find any trick
3. given any trick you can quickly display the config
4. given multiple parameters from the user, you can filter this array down to what you do care about

this allows for more of a programatic approach instead of having to wrap your head around shuv logic or any nested if/elses

**Comment by cunnellp5** [comment]
the obstacles array might need a little more consideration, but maybe good for now

**Comment by Payton212** [comment]
I think im understanding it more now to and i do like it! it will end up being big tho! once we have like 
const tricksLibrary = [
  { 
    trickName: 'treflip Crook',
    trickConfig: {
        stance: STANCES.REGULAR,
        direction: DIRECTIONS.NONE,
        bodyRotation: 0,
        shuvRotation: 360,
        flip: FLIPS.kickflip,
    },
    obstacles: ['flatbar', 'hubba', 'ledge','downrail'],
    difficulty: DIFFICULTY.Extreme
  },
]

**Comment by Payton212** [comment]
then mapping that is gonna get wild
also is that about what it would end up looking like?

**Comment by cunnellp5** [comment]
i dont think you'd want to combine two tricks like that in the tricksLibrary
you'd likely want to pull the two objects from the tricksLibrary and combine them separately

the goal is to keep the tricksLibrary object as flat as possible and outline every single trick. 
Combos should be calculated dynamically

**Comment by Payton212** [comment]
Okay I think that’s what I was struggling to wrap my head around, so will just a basic crook be in trick library or obstacle.hubba.crook
